sudo: required
services:
  - docker

before_install:
  - docker build -t joseahumada/dockertest2 -f Dockerfile.dev .


script:
  - docker run -e CI=true joseahumada/dockertest3 npm run test -- --watchAll=false
