sudo: required
services:
  - docker

before_install:
  - docker build -t joseahumada/dockertest3 -f Dockerfile.dev .


script:
  - docker run -e CI=true joseahumada/dockertest3 npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "dockerweb"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-594250092736"
  bucket_path: "dockerweb"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:  
    secure: "$AWS_SECRET_KEY"
  
